#!/bin/sh

case "$1" in
"start")
  echo "start-loading..."
  scull_load
  module_load faulty
  modprobe hello
  ;;
"stop")
  echo "stop-unloading..."
  scull_unload
  module_unload faulty
  rmmod hello
  ;;
*)
  echo "Usage: $0 [start|stop]"
  ;;
esac


